from distutils.core import setup
setup(
    name='cookiecutter-starlette-service',
    packages=[],
    version='0.1.0',
    description='Cookiecutter template for a Starlette Application',
    author='Biola',
    license='BSD',
    author_email='b33sama@gmail.com',
    url='https://github.com/gbozee/cookiecutter-starlette-service',
    keywords=['cookiecutter', 'template', 'package','starlette' ],
    python_requires='>=3.6',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Software Development',
    ],
)