site_name: {{cookiecutter.project_name.replace("-"," ").title()}}

theme:
    name: 'material'
    palette:
      primary: 'blue'
      accent: 'blue'
# Customization
extra:
  social:
    - type: globe
      link: http://struct.cc
    - type: github-alt
      link: https://github.com/squidfunk
    - type: twitter
      link: https://twitter.com/squidfunk
    - type: slack
      link: https://linkedin.com/in/squidfunk
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  # - Customization: customization.md
  # - Compliance with GDPR: compliance.md
  # - Release notes: release-notes.md
  # - Author's notes: authors-notes.md
  # - Contributing: contributing.md
  # - License: license.md